### PR TITLE
Added error handling for non-numbers and non-integers

### PR DESCRIPTION
**Pull request by dwaffle**
Switches the if block to a try-except, allowing for throwing a ValueError when the user inputs invalid values.

### CODE REVIEW

**Comment by christopher-chandler** [comment]
I like the idea! I add an error message in an info box in my commit though.

**Review by IceTheDev2 — APPROVED** [review]
Thank you!

**Comment by christopher-chandler** [comment]
no prob !

**Comment by dwaffle** [comment]
You're welcome - now I wonder if people might think "An error occurred, try again with a non-integer greater than 0" is a password.  I suppose it is a reasonably secure password at least..

**Pull request merged**
